name: Generate Channel ID JSON

on:
  push:
    branches:
      - main

jobs:
  generate-json:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install nextcord

    - name: Run script
      run: python generate_channelid_json.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        SERVER_ID: ${{ secrets.SERVER_ID }}
