name: Run Discord Bot
on:
  schedule:
    - cron:  '40 11 * * *'  # UTCで表現すると日本時間の20:40はUTCの11:40です。

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Discord bot
      run: python main.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        LOG_LEVEL: ${{ secrets.LOG_LEVEL }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        SUMMARY_CHANNEL_NAME: ${{ secrets.SUMMARY_CHANNEL_NAME }}
