name: Run Discord Bot
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 15 * * *'  # JSTの0時はUTCの15時です。

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Discord bot
      run: python main.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        SUMMARY_CHANNEL_ID: ${{ secrets.SUMMARY_CHANNEL_ID }}
