name: Run Discord Bot
on:
  workflow_dispatch:
  schedule:
    - cron:  '1 15 * * *'  # 日本時間の00:01はUTCの前日の15:01です。

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate JSON from Discord chat
      run: python generate_json.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        SUMMARY_CHANNEL_ID: ${{ secrets.SUMMARY_CHANNEL_ID }}
    - name: Summarize Discord chat
      run: python summarize_chat.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        SUMMARY_CHANNEL_NAME: ${{ secrets.SUMMARY_CHANNEL_NAME }}
    - name: Send summary to Discord
      run: python send_summary.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        GUILD_ID: ${{ secrets.GUILD_ID }}
        SUMMARY_CHANNEL_ID: ${{ secrets.SUMMARY_CHANNEL_ID }}
    - name: Run Proposal Zatsudan Summary
      run: python proposal_zatsudan_summary.py
      env:
        DISCORD_TOKEN: ${{ secrets.DISCORD_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        CHANNEL_IDS: ${{ secrets.CHANNEL_IDS }}
